### ISSUE TITLE
yosys can't find random.mem

### ISSUE THREAD

**Issue by olofk** [siliconcompiler/zerosoc#17] opened 2021-12-14 16:14 UTC
./build --fpga eventually gives me
```
2.110. Executing AST frontend in derive mode using pre-parsed AST for module `\prim_generic_ram_1p'.
inputs/top_icebreaker.v:0: ERROR: Can not open file ``MEM_ROOT/random.mem` for \$readmemh.
```

I haven't fully analyzed the situation but my guess right now is that the import step is assumed to expand that var and that it never gets sent to yosys. I'm a bit confused about the toolchain in play here also. I don't have surelog installed but it seems to proceed anyway. Is it using sv2v as a fallback here?

**Comment by olofk** [comment] 2021-12-14 16:14
To clarify. Build works fine if I hard code the path in top_icebreaker.v

**Comment by nmoroze** [comment] 2021-12-16 18:39
Thanks for reporting this issue! 

Good question about the toolchain, I'll explain that first to provide context for the root cause of this issue. The first few steps work as follows:

1) Surelog runs in the 'import' step to gather files and produce a single pickled (System)Verilog file. 
2) sv2v runs in the 'convert' step to convert the pickled SystemVerilog to Verilog.
3+) Yosys synthesizes the converted Verilog, and passes the netlist along to OpenROAD for floorplanning, place & route, etc. 

The trick here is that we actually bundle a Surelog binary with the Python wheels we distribute, so you don't need to install it explicitly. We do this to support a zero tool install setup if you're just using the remote flow (we rely on running Surelog locally for remote flows in order to process inputs that are provided via -y or -I flags rather than specified explicitly). 

The problem here is we accidentally reverted the version of Surelog bundled with the wheels to one that has a known bug in the preprocessor. Once this [PR](https://github.com/siliconcompiler/siliconcompiler/pull/800) is merged and we make a new release I'll close the issue, but in the meantime you can work around this by building Surelog [5b07b264b3](https://github.com/chipsalliance/Surelog/tree/5b07b264b3f1a115ee1a747ede6e532fdf089d49). Any Surelog installed on your path will take precedence over the bundled binary.

**Comment by nmoroze** [comment] 2021-12-21 20:25
This should be fixed now in SC 0.3. Let me know if you run into this issue again!

**Closed by nmoroze** 2021-12-21 20:25 UTC
